services:
  postgres:
    image: postgres:15.13
    container_name: postgres
    environment:
      POSTGRES_DB: ${PG_DB_TAG}
      POSTGRES_USER: ${PG_USER_TAG}
      POSTGRES_PASSWORD: ${PG_PASSWORD_TAG}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready","-U","keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - general-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${PG_DB_TAG}
      KC_DB_USERNAME: ${PG_USER_TAG}
      KC_DB_PASSWORD: ${PG_PASSWORD_TAG}
      KEYCLOAK_ADMIN: ${KC_ADMIN_TAG}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD_TAG}
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    command:
      - start-dev
    ports:
      - "80:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - general-network

volumes:
  postgres_data:
    name: postgres_data
  
networks:
  general-network:
    name: general-network  





