services:
  webserver:
    image: nginx:1.28.0-alpine
    container_name: web-nginx
    hostname: web-nginx
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
